#!/bin/sh

# Search reference tree located at $REFS using fzf
# Based on https://github.com/bellecp/fast-p

MINIREF_HOME=${MINIREF_HOME:-${HOME}/miniref}

# Execute ref_summarise.sh separately on directories in tree rooted at $MINIREF_HOME.
# For preview: Split off summary information generated by ref_summarise.sh.
#   If ref.ris is present, add it to the summary, followed by a list of files contained in the directory.
#   Note the need to escape { and }, since these would be expanded to the current entry by fzf (we want find to perform the expansion).
# For <enter> binding, split off summary information.
# For <F1> key binding split off summary information, then execute refview.sh once with all directories in selected tree as arguments.
echo "${MINIREF_HOME}/$(cd "$MINIREF_HOME" && find . -type d -exec ref_summarise.sh {} \; |
 	fzf --read0 --reverse \
    --preview 'k=$(echo {} | /usr/bin/cut -f-1) && test -f "$k"/ref.ris && cat "$k"/ref.ris; echo "---"; test -f "$k"/tags && cat "$k"/tags | tr "\n" " " && echo ""; echo "---"; find "$k" -maxdepth 1 -type f -iname "*.txt" -exec cat \{\} +' \
    --bind 'f1:execute(k=$(echo {} | cut -f-1) && refview.sh "$k")' \
    --preview-window='wrap' |
    cut -f1
)"
