#!/bin/sh

# Search reference tree located at $REFS using fzf
# Based on https://github.com/bellecp/fast-p

if test -z "$REFS"; then
    echo "REFS environment variable is not set" 1>&2
    exit 1
fi

# Execute ref_summarise.sh separately on directories in tree rooted at $REFS.
# For preview: Split off summary information generated by ref_summarise.sh.
#   If ref.ris is present, add it to the summary, followed by a list of files contained in the directory.
#   Note the need to escape { and }, since these would be expanded to the current entry by fzf (we want find to perform the expansion).
# For <enter> binding, split off summary information, then become a shell in that directory.
# For <F1> key binding split off summary information, then execute refview.sh once with all directories in selected tree as arguments.
( cd "$REFS" && find . -type d -exec ref_summarise.sh {} \; |
 	fzf --read0 --reverse \
    --preview 'k=$(echo {} | /usr/bin/cut -f-1) && test -f "$k"/ref.ris && cat "$k"/ref.ris; echo "---"; find "$k" -maxdepth 1 -type f -exec basename \{\} \;; echo "---"; txt=$( find "$k" -maxdepth 1 -type f -iname "*.txt" | head -1 ) && test ! -z "$txt" && cat "$k"/*.txt' \
    --bind 'enter:become(k=$(echo {} | cut -f-1) && cd "$k" && $SHELL)' \
    --bind 'f1:execute(k=$(echo {} | cut -f-1) && find "$k" -type d -exec refview.sh \{\} +)'
)
